downloaders:
  reddit:
    id:
    secret:
    useragent: blink
    user: medlemOV
    password:
    subreddits:
      - pics
      - EarthPorn
    params:
      download_batch_size: 1000 #How many images to attempt downloading per subreddit (MAX: 1000)
      time_refresh_sub: 30 #In minutes: How long to wait between updating list of posts
      update_interval: 30
      show_top_comment: True
      max_log_size: 1000 #Keep track of this many media elements we have already shown.

  imgur:
    param: 1
  pixiv:
    param: 1

themes:
  monday:
    reddit:
      - miku
      - hatsunemiku
      - miggu
  wednesday:
    reddit:
      - me_irl
      - meirl
      - absolutelynotme_irl

params:
  image_duration: 10 #Shows images for this amount of seconds
  min_gif_duration: 15 #Show gifs for at least this amount of seconds
  max_gif_duration: 100 #Show gifs for maximum this amount of seconds
  gif_iterations: 2 #Optimally, show gifs for this amount of iterations. min_gif_duration and max_gif_duration supersedes this config
  time_delay_text: 5 #Waits this amount of seconds before showing text overlay. Must be larger than image_duration.
  max_queue_size: 10 #How many images to store before showing
  media_filepath: /home/omegav/git/Blink/images
  log_filepath: /home/omegav/git/Blink/logs
  min_aspect_ratio: 0.5
  max_aspect_ratio: 3
  title_font_size: 30




